version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    env_file:
      - .env.testing
    volumes:
      - mysql-testing-data:/var/lib/mysql
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/0.sql
    ports:
      - 3306:3306
    networks:
      - my-network
    command: --default-authentication-plugin=mysql_native_password
        
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.testing
    ports:
      - 5000:5000
    networks:
      - my-network
    command:  sh -c "pip install cryptography==40.0.2 pytest==7.3.1 && wait-for-it.sh mysql-container:3306 -t 60 && flask db upgrade && python -m pytest -s ./app/tests"
    
volumes:
  mysql-testing-data:

networks:
  my-network:
