"""Update models

Revision ID: 594cdb8f0a4c
Revises: 441896bfdb68
Create Date: 2023-06-28 20:56:10.121473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594cdb8f0a4c'
down_revision = '441896bfdb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('curtain_call', sa.String(
                        length=255), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_url'), ['url'], unique=True)

    op.create_table('options',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('poll_id', sa.Integer(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('movie_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('imdb_url', sa.String(
                        length=255), nullable=True),
                    sa.Column('rotten_tomatoes_url', sa.String(
                        length=255), nullable=True),
                    sa.Column('stream_url', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table(
        'option_votes',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('option_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['option_id'], ['options.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_url'))

    op.drop_table('polls')
    op.drop_table('option_votes')
    # ### end Alembic commands ###
